---
# Build and run the Go binary from the repo
# REQUIRES: Go v1.16+ installed
- id: ansdoc-go
  name: ansdoc
  description: Generate documentation for Ansible Roles (via Go binary)
  language: golang
  entry: ansdoc
  pass_filenames: false
  types: [yaml]

# Build and run `ansdoc` assuming it was installed manually
# or via package manager
# REQUIRES: ansdoc to be installed and on the $PATH
- id: ansdoc-system
  name: ansdoc
  description: Generate documentation for Ansible Roles (via locally-installed CLI)
  language: system
  entry: ansdoc
  pass_filenames: false
  types: [yaml]

# Builds and runs the Docker image from the repo
# REQUIRES: Docker installed
- id: ansdoc-docker
  name: ansdoc
  description: Generate documentation for Ansible Roles (via Docker build)
  language: docker
  entry: ansdoc
  pass_filenames: false
  types: [yaml]
